/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : bigint,
  'name' : string,
  'description' : string,
}
export interface Question {
  'id' : bigint,
  'categoryId' : bigint,
  'difficulty' : string,
  'questionText' : string,
  'correctOptionIndex' : bigint,
  'options' : Array<string>,
}
export interface Test {
  'id' : bigint,
  'categoryId' : bigint,
  'title' : string,
  'createdBy' : Principal,
  'timeLimitMinutes' : bigint,
  'questionIds' : Array<bigint>,
}
export interface TestAttempt {
  'userName' : string,
  'userId' : Principal,
  'answers' : Array<bigint>,
  'score' : bigint,
  'totalQuestions' : bigint,
  'timestamp' : Time,
  'testId' : bigint,
}
export interface TestResult {
  'score' : bigint,
  'totalQuestions' : bigint,
  'correctAnswers' : bigint,
  'details' : Array<[bigint, boolean]>,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimAdminWithSecret' : ActorMethod<[string], boolean>,
  'createCategory' : ActorMethod<[string, string], bigint>,
  'createQuestion' : ActorMethod<
    [bigint, string, Array<string>, bigint, string],
    bigint
  >,
  'createTest' : ActorMethod<[string, bigint, Array<bigint>, bigint], bigint>,
  'deleteCategory' : ActorMethod<[bigint], undefined>,
  'deleteQuestion' : ActorMethod<[bigint], undefined>,
  'deleteTest' : ActorMethod<[bigint], undefined>,
  'deleteUserScoreRecord' : ActorMethod<[Principal, Time], undefined>,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getAllDataPublic' : ActorMethod<
    [],
    {
      'categories' : Array<Category>,
      'tests' : Array<Test>,
      'questions' : Array<Question>,
      'isAuthenticated' : boolean,
    }
  >,
  'getAllQuestions' : ActorMethod<[], Array<Question>>,
  'getAllTestAttempts' : ActorMethod<[], Array<TestAttempt>>,
  'getAllTests' : ActorMethod<[], Array<Test>>,
  'getCallerTestAttempts' : ActorMethod<[], Array<TestAttempt>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategory' : ActorMethod<[bigint], Category>,
  'getQuestion' : ActorMethod<[bigint], Question>,
  'getQuestionsByCategory' : ActorMethod<[bigint], Array<Question>>,
  'getTest' : ActorMethod<[bigint], Test>,
  'getTestResult' : ActorMethod<[bigint, Array<bigint>], TestResult>,
  'getTestsByCategory' : ActorMethod<[bigint], Array<Test>>,
  'getTopScores' : ActorMethod<[], Array<TestAttempt>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTestAttempts' : ActorMethod<[Principal], Array<TestAttempt>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'register' : ActorMethod<[], undefined>,
  'resetAllScores' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedData' : ActorMethod<[], undefined>,
  'submitTestAttempt' : ActorMethod<[bigint, Array<bigint>, string], undefined>,
  'updateCategory' : ActorMethod<[bigint, string, string], undefined>,
  'updateQuestion' : ActorMethod<
    [bigint, bigint, string, Array<string>, bigint, string],
    undefined
  >,
  'updateTest' : ActorMethod<
    [bigint, string, bigint, Array<bigint>, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];