/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Category = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Test = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'title' : IDL.Text,
  'createdBy' : IDL.Principal,
  'timeLimitMinutes' : IDL.Nat,
  'questionIds' : IDL.Vec(IDL.Nat),
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'difficulty' : IDL.Text,
  'questionText' : IDL.Text,
  'correctOptionIndex' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const TestAttempt = IDL.Record({
  'userName' : IDL.Text,
  'userId' : IDL.Principal,
  'answers' : IDL.Vec(IDL.Nat),
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'timestamp' : Time,
  'testId' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TestResult = IDL.Record({
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'correctAnswers' : IDL.Nat,
  'details' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Bool)),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimAdminWithSecret' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'createCategory' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'createQuestion' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createTest' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Vec(IDL.Nat), IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'deleteCategory' : IDL.Func([IDL.Nat], [], []),
  'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
  'deleteTest' : IDL.Func([IDL.Nat], [], []),
  'deleteUserScoreRecord' : IDL.Func([IDL.Principal, Time], [], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getAllDataPublic' : IDL.Func(
      [],
      [
        IDL.Record({
          'categories' : IDL.Vec(Category),
          'tests' : IDL.Vec(Test),
          'questions' : IDL.Vec(Question),
          'isAuthenticated' : IDL.Bool,
        }),
      ],
      ['query'],
    ),
  'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getAllTestAttempts' : IDL.Func([], [IDL.Vec(TestAttempt)], ['query']),
  'getAllTests' : IDL.Func([], [IDL.Vec(Test)], ['query']),
  'getCallerTestAttempts' : IDL.Func([], [IDL.Vec(TestAttempt)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategory' : IDL.Func([IDL.Nat], [Category], ['query']),
  'getQuestion' : IDL.Func([IDL.Nat], [Question], ['query']),
  'getQuestionsByCategory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getTest' : IDL.Func([IDL.Nat], [Test], ['query']),
  'getTestResult' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Nat)],
      [TestResult],
      ['query'],
    ),
  'getTestsByCategory' : IDL.Func([IDL.Nat], [IDL.Vec(Test)], ['query']),
  'getTopScores' : IDL.Func([], [IDL.Vec(TestAttempt)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTestAttempts' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(TestAttempt)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'register' : IDL.Func([], [], []),
  'resetAllScores' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedData' : IDL.Func([], [], []),
  'submitTestAttempt' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat), IDL.Text], [], []),
  'updateCategory' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateQuestion' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updateTest' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Vec(IDL.Nat), IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Category = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Test = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'title' : IDL.Text,
    'createdBy' : IDL.Principal,
    'timeLimitMinutes' : IDL.Nat,
    'questionIds' : IDL.Vec(IDL.Nat),
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'difficulty' : IDL.Text,
    'questionText' : IDL.Text,
    'correctOptionIndex' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const TestAttempt = IDL.Record({
    'userName' : IDL.Text,
    'userId' : IDL.Principal,
    'answers' : IDL.Vec(IDL.Nat),
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'timestamp' : Time,
    'testId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TestResult = IDL.Record({
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'correctAnswers' : IDL.Nat,
    'details' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Bool)),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimAdminWithSecret' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'createCategory' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'createQuestion' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createTest' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Vec(IDL.Nat), IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'deleteCategory' : IDL.Func([IDL.Nat], [], []),
    'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
    'deleteTest' : IDL.Func([IDL.Nat], [], []),
    'deleteUserScoreRecord' : IDL.Func([IDL.Principal, Time], [], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getAllDataPublic' : IDL.Func(
        [],
        [
          IDL.Record({
            'categories' : IDL.Vec(Category),
            'tests' : IDL.Vec(Test),
            'questions' : IDL.Vec(Question),
            'isAuthenticated' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getAllTestAttempts' : IDL.Func([], [IDL.Vec(TestAttempt)], ['query']),
    'getAllTests' : IDL.Func([], [IDL.Vec(Test)], ['query']),
    'getCallerTestAttempts' : IDL.Func([], [IDL.Vec(TestAttempt)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategory' : IDL.Func([IDL.Nat], [Category], ['query']),
    'getQuestion' : IDL.Func([IDL.Nat], [Question], ['query']),
    'getQuestionsByCategory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getTest' : IDL.Func([IDL.Nat], [Test], ['query']),
    'getTestResult' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Nat)],
        [TestResult],
        ['query'],
      ),
    'getTestsByCategory' : IDL.Func([IDL.Nat], [IDL.Vec(Test)], ['query']),
    'getTopScores' : IDL.Func([], [IDL.Vec(TestAttempt)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTestAttempts' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(TestAttempt)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'register' : IDL.Func([], [], []),
    'resetAllScores' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedData' : IDL.Func([], [], []),
    'submitTestAttempt' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Nat), IDL.Text],
        [],
        [],
      ),
    'updateCategory' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateQuestion' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updateTest' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Vec(IDL.Nat), IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };